### ISSUE TITLE
觉得想法很好，想一起参与这个awesome list的修改

### ISSUE THREAD

**Issue by brandonxiang** [sshuair/awesome-gis#1]
我的几点小建议
1. 应该要加一个CONTRIBUTING.md，如awesome-python的[CONTRIBUTING.md](https://github.com/vinta/awesome-python/blob/master/CONTRIBUTING.md)，引导大家参与修改。
2. 感觉外国的awesome-list都不喜欢用**分点**，如1.，1.1，1.2，1.2.1，直接用header和分割线就好。
3. 当然每个软件的介绍还需再详细一点。

**Comment by sshuair** [comment]
nice advices，欢迎参与完善

**Comment by sshuair** [comment]
前两点已修改，看看还有哪里需要完善的，第三点以后有空慢慢加

**Comment by sshuair** [comment]
另外你在知乎上的[回答](https://www.zhihu.com/question/20746494/answer/95374531)，我觉得有不少新内容，可以加入进来

**Comment by brandonxiang** [comment]
好的，等有空的时候，整理一下加进来
