### ISSUE TITLE
How to use python in service area without Arcgis?

### ISSUE THREAD

**Issue by ZGarry** [sshuair/awesome-gis#73]
Now I search a lot but still can not find a python-package in it.

There is the work I finished. 
1.search "PYTHON service area"
2.read some package like shapely,pysal and more. But can find one.

**Comment by sshuair** [comment]
A lot of python services you can use flask, django.... 
It's not design for GIS but you can use gis package with it.

BTW, it's not related with this Repo, you can ask on Reddit or Stackoverflow.
