### ISSUE TITLE
GeoDjango URL is out of date

### ISSUE THREAD

**Issue by pcbock** [sshuair/awesome-gis#96]
The current link under Web Map Servers for GeoDjango is out of date.  The current link yields:

![image](https://user-images.githubusercontent.com/11447724/96514005-0ca88400-1231-11eb-80c1-2bf35124b7cd.png)

Current information appears to be located here:

https://docs.djangoproject.com/en/3.1/ref/contrib/gis/tutorial/

**Comment by sshuair** [comment]
fixed
